# Generated by Django 3.1.1 on 2022-10-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221030_1505'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenItem',
            new_name='MenuItem',
        ),
    ]
