# Generated by Django 3.1.1 on 2022-10-30 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clockify_reporter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenItem',
        ),
    ]
